baseURL = "https://www.assist-secretariat.com/"
languageCode = "fr"
title = "AOGW"
description = "Armelle votre Assistante de Direction vous offre un service personnalisé, sur site ou à distance."
themesDir = "themes"
theme = "hugo-hero-theme-master"
enableRobotsTXT = true
canonifyURLs = true


[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
  [[module.mounts]]
    source = "static"
    target = "assets"
  [[module.mounts]]
    source = "static"
    target = "static"

    
[sitemap]
changefreq = "weekly"
filename = "sitemap.xml"
priority = 0.5

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 2


[params]
  google_analytics_id=""


  [params.homepage_meta_tags]
    meta_description = "A. Office Gestion Web assiste les dirigeants d'Entreprise, sur site ou à distance."
    meta_og_title = "AOGW - A. Office Gestion Web"
    meta_og_type = "website"
    meta_og_url = "https://www.assist-secretariat.com/"
    meta_og_image = ""
    meta_og_description = "A. Office Gestion Web assiste les dirigeants d'Entreprise, sur site ou à distance."


[[menu.main]]
    name = "Accueil"
    url = "/index.html/"
    weight = 1

[[menu.main]]
    name = "Prestations"
    url = "/prestations/"
    weight = 1

##[[menu.main]]
##    name = "Avantages"
##    url = "/avantages/"
##    weight = 2

[[menu.main]]
    name = "Qui suis-je"
    url = "/quisuisje/"
    weight = 4

[[menu.main]]
    name = "Tarifs"
    url = "/tarifs/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5
    

[permalinks]
  post = "/:year/:month/:day/:title/"
  pages = "/:filename/"
