baseURL = "/"
languageCode = "fr"
title = "AOGW"
themesDir = "themes"
theme = "hugo-hero-theme-master"
enableRobotsTXT = true
canonifyURLs = true


[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/aogw-logo-200w.png"
    desktop = "images/aogw-logo-400w.png"
    alt = "Logo AOGW"

  [params.homepage_meta_tags]
    meta_description = "A. Office Gestion Web assiste les dirigeants d'Entreprise, sur site ou à distance."
    meta_og_title = "AOGW - A. Office Gestion Web"
    meta_og_type = "website"
    meta_og_url = "https://www.assist-secretariat.com/"
    meta_og_image = ""
    meta_og_description = "A. Office Gestion Web assiste les dirigeants d'Entreprise, sur site ou à distance."


[[menu.main]]
    name = "Prestations"
    url = "/prestations/"
    weight = 1

[[menu.main]]
    name = "Avantages"
    url = "/avantages/"
    slug = "avantages"
    weight = 2

[[menu.main]]
    name = "Qui suis-je"
    url = "/quisuisje/"
    weight = 4

[[menu.main]]
    name = "Tarifs"
    url = "/tarifs/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5
    

[permalinks]
  post = "/:year/:month/:day/:title/"
  pages = "/:filename/"
