backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: themes/hugo-hero-theme-master/assets/img
public_folder: /img
collections:
  - name: 'prestations'
    label: 'Prestations'
    folder: 'content/prestations'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Summary', name: 'summary', widget: 'string' }     
      - { label: 'Body', name: 'body', widget: 'markdown' }
      
  - name: 'avantages'
    label: 'Avantages'
    folder: 'content/avantages'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'heroHeading', name: 'heroHeading', widget: 'string' } 
      - { label: 'heroSubHeading', name: 'heroSubHeading', widget: 'string' } 
      - { label: 'thumbnail', name: 'thumbnail', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      
  - name: 'tarifs'
    label: 'Tarifs'
    folder: 'content/pages/tarifs'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Summary', name: 'summary', widget: 'string' }     
      - { label: 'Body', name: 'body', widget: 'markdown' }
      
  - name: 'about'
    label: 'Qui suis-je'
    folder: 'content/pages/quisuisje'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Summary', name: 'summary', widget: 'string' }     
      - { label: 'Body', name: 'body', widget: 'markdown' }
      
  - name: 'mentionslegales'
    label: 'Mentions légales'
    folder: 'content/mentionslegales'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Summary', name: 'summary', widget: 'string' }     
      - { label: 'Body', name: 'body', widget: 'markdown' }
