backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

site_url: https://www.assist-secretariat.com
display_url: https://www.assist-secretariat.com
logo_url: https://www.assist-secretariat.com/images/aogw-logo-400w.png
locale: 'fr'

media_folder: themes/hugo-hero-theme-master/assets/img
public_folder: /img
collections:
  - name: 'section prestations'
    label: 'Section Prestations'
    folder: 'content/prestations'
    create: true
    editor:
      preview: true
    filter: {fields: "mainsection", value: "true"}
    fields:
      - { label: 'Titre SEO', name: 'title', widget: 'string' }
      - { label: 'Description SEO', name: 'description', widget: 'string' }
      - { label: 'Titre de la Page', name: 'heroHeading', widget: 'string' }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }
  - name: 'prestations'
    label: 'Mes Prestations'
    folder: 'content/prestations'
    create: true
    editor:
      preview: true
    filter: {fields: "mainsection", value: "false"}
    fields:
      - { label: 'Intitulé sous-section et Titre SEO', name: 'title', widget: 'string' }
      - { label: 'Description SEO', name: 'description', widget: 'string' }
      - { label: 'Icone', name: 'icon', widget: 'image' }
      - { label: 'Ordre', name: 'weight', widget: 'number' }
      - { label: 'Titre de la Page', name: 'heroHeading', widget: 'string' }
      - { label: 'Résumé', name: 'summary', widget: 'string' }
      - { label: 'Contenu', name: 'body', widget: 'markdown' }

  - name: 'avantages'
    label: 'Avantages'
    folder: 'content/avantages'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'SEO Title', name: 'title', widget: 'string' }
      - { label: 'SEO Description', name: 'description', widget: 'string' }
      - { label: 'Title Page', name: 'heroHeading', widget: 'string' } 
      - { label: 'Subtitle Page', name: 'heroSubHeading', widget: 'string' } 
      - { label: 'Banner Image', name: 'heroBackground', widget: 'image' }
      - { label: 'Thumbnail', name: 'thumbnail', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      
  - name: 'tarifs'
    label: 'Tarifs'
    folder: 'content/pages/tarifs'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Summary', name: 'summary', widget: 'string' }     
      - { label: 'Body', name: 'body', widget: 'markdown' }
      
  - name: 'mentionslegales'
    label: 'Mentions légales'
    folder: 'content/mentionslegales'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'SEO Title', name: 'title', widget: 'string' }
      - { label: 'SEO Description', name: 'description', widget: 'string' }
      - { label: 'Title Page', name: 'heroHeading', widget: 'string' } 
      - { label: 'Subtitle Page', name: 'heroSubHeading', widget: 'string' } 
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - label: 'Qui suis je'
    name: 'quisuisje'
    files:
      - label: 'Qui suisje'
        name: 'index'
        file: 'content/pages/quisuisje/index.md'
        fields:
        - { label: 'SEO Title', name: 'title', widget: 'string' }
        - { label: 'SEO Description', name: 'description', widget: 'string' }
        - { label: 'Title Page', name: 'heroHeading', widget: 'string' } 
        - { label: 'Subtitle Page', name: 'heroSubHeading', widget: 'string' } 
      - label: 'A mes débuts'
        name: 'content1'
        file: 'content/pages/quisuisje/content1.md'
        fields:
        - { label: 'SEO and Page Title', name: 'title', widget: 'string' }
        - { label: 'SEO Description', name: 'description', widget: 'string' }
        - { label: 'Body', name: 'body', widget: 'markdown' }
